language: ruby
env: RECHARGE_TEST_DB=http://localhost:5984/recharge_travis
before_script: "curl -X PUT $RECHARGE_TEST_DB"
services:
  - couchdb
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
rvm:
  - 1.9.2